-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, b.SCORE
FROM REST_INFO a, 
    (
        SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
        FROM REST_REVIEW
        GROUP BY REST_ID
    ) b
WHERE a.REST_ID = b.REST_ID AND a.ADDRESS LIKE '서울%'
ORDER BY b.SCORE DESC, a.FAVORITES DESC