
SELECT B.USER_ID, B.NICKNAME, A.PRICE AS TOTAL_SALES
FROM 
    (SELECT WRITER_ID, SUM(PRICE) AS PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID) A, USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID AND A.PRICE >= 700000
ORDER BY TOTAL_SALES ASC





